# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cjgammon
email: cj.gammon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of cjgammon, discussing technology and creativity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.cjgammon.com" # the base hostname & protocol for your site
homepage: "http://www.cjgammon.com"
twitter_username: cjgammon
github_username:  cjgammon
permalink: :title
exclude: [_site, README.md]
paginate: 10
# Build settings
markdown: kramdown
gems:
- jekyll-paginate
- jekyll-babel
- jekyll-redirect-from
